sudo: required
language: python
jdk: openjdk8

python:
  - "3.6"

services:
  - docker

install:
  - "pip install -r tests/requirements-test.txt"
  # Install Nextflow
  - mkdir /tmp/nextflow
  - cd /tmp/nextflow
  - wget -qO- -t10 get.nextflow.io | bash
  - chmod 755 /tmp/nextflow/nextflow
  - sudo ln -s /tmp/nextflow/nextflow /usr/local/bin/nextflow
  - cd ${TRAVIS_BUILD_DIR}

script: 
  - pytest -v
